
package com.Marc.Kalamus.GUI;

import com.Marc.Kalamus.Modelo.Planeta;
import com.Marc.Kalamus.Persistencia.KalamusDB;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class BeingAdd extends javax.swing.JFrame {

    public BeingAdd(KalamusDB kalamusDB) {
        initComponents();
        grup.add(masculi);
        grup.add(femeni);
        grupNibirian.add(flora);
        grupNibirian.add(peixos);
        this.kalamusDB=kalamusDB;
        ArrayList<Planeta> llistaPlanetas = kalamusDB.getPlanetas();
        for(int i=0;  i< llistaPlanetas.size(); i++){
            comboPlaneta.addItem(llistaPlanetas.get(i).getNom());
        }
        amagar();
    }
    private KalamusDB kalamusDB;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grup = new javax.swing.ButtonGroup();
        grupNibirian = new javax.swing.ButtonGroup();
        Home = new javax.swing.JButton();
        enviar = new javax.swing.JButton();
        textNom = new javax.swing.JTextField();
        nom = new javax.swing.JLabel();
        comboPlaneta = new javax.swing.JComboBox<>();
        planeta = new javax.swing.JLabel();
        comboEspecie = new javax.swing.JComboBox<>();
        especie = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        andorian = new javax.swing.JPanel();
        comboRang = new javax.swing.JComboBox<>();
        rang = new javax.swing.JLabel();
        aenar = new javax.swing.JLabel();
        comboAenar = new javax.swing.JComboBox<>();
        nibirian = new javax.swing.JPanel();
        peixos = new javax.swing.JRadioButton();
        alimentacio = new javax.swing.JLabel();
        flora = new javax.swing.JRadioButton();
        vulcanian = new javax.swing.JPanel();
        comboMeditacio = new javax.swing.JComboBox<>();
        meditacio = new javax.swing.JLabel();
        huma = new javax.swing.JPanel();
        textEdat = new javax.swing.JTextField();
        genere = new javax.swing.JLabel();
        masculi = new javax.swing.JRadioButton();
        femeni = new javax.swing.JRadioButton();
        edat = new javax.swing.JLabel();
        ferengi = new javax.swing.JPanel();
        textLantanium = new javax.swing.JTextField();
        lantanium = new javax.swing.JLabel();
        klingon = new javax.swing.JPanel();
        força = new javax.swing.JLabel();
        slicerForça = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));
        getContentPane().add(textNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 50, 84, -1));

        nom.setText("Nom");
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 53, -1, -1));

        getContentPane().add(comboPlaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 116, 84, -1));

        planeta.setText("Planeta");
        getContentPane().add(planeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 119, -1, -1));

        comboEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andorian", "Huma", "Ferengi", "Vulcanian", "Klingon", "Nibirian" }));
        comboEspecie.setSelectedIndex(-1);
        comboEspecie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEspecieItemStateChanged(evt);
            }
        });
        getContentPane().add(comboEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 84, -1, -1));

        especie.setText("Especie");
        getContentPane().add(especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 87, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Afegeix un esser");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        andorian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboRang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lluitador", "Entrenador", "Defensor", "Cavaller" }));
        andorian.add(comboRang, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 6, -1, -1));

        rang.setText("Rang");
        andorian.add(rang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        aenar.setText("Aenar");
        andorian.add(aenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, -1, -1));

        comboAenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        andorian.add(comboAenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 40, 92, -1));

        getContentPane().add(andorian, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 156, 150, -1));

        nibirian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        peixos.setText("Peixos");
        nibirian.add(peixos, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 6, -1, -1));

        alimentacio.setText("Alimentacio");
        nibirian.add(alimentacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 8, -1, -1));

        flora.setText("Flora Vermella");
        nibirian.add(flora, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 6, -1, -1));

        getContentPane().add(nibirian, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 156, -1, -1));

        vulcanian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboMeditacio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        vulcanian.add(comboMeditacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 6, -1, -1));

        meditacio.setText("Meditacio");
        vulcanian.add(meditacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        getContentPane().add(vulcanian, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 156, 160, 50));

        huma.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        huma.add(textEdat, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 6, 71, -1));

        genere.setText("Genere");
        huma.add(genere, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, -1, -1));

        masculi.setSelected(true);
        masculi.setText("Masculi");
        huma.add(masculi, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 40, -1, -1));

        femeni.setText("Femeni");
        huma.add(femeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 40, -1, -1));

        edat.setText("Edat");
        huma.add(edat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, -1, -1));

        getContentPane().add(huma, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 156, -1, -1));

        ferengi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ferengi.add(textLantanium, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 6, 71, -1));

        lantanium.setText("Lantanium");
        ferengi.add(lantanium, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        getContentPane().add(ferengi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        klingon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        força.setText("Força");
        klingon.add(força, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, -1, -1));

        slicerForça.setMajorTickSpacing(1);
        slicerForça.setMaximum(350);
        slicerForça.setMinimum(50);
        slicerForça.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slicerForçaStateChanged(evt);
            }
        });
        klingon.add(slicerForça, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 6, -1, -1));

        jLabel2.setText("50");
        klingon.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 6, -1, -1));

        getContentPane().add(klingon, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 156, 300, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void comboEspecieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEspecieItemStateChanged
        amagar();
        switch(evt.getItem().toString()){
           case "Huma":
               huma.setVisible(true);
               break;
               
           case "Andorian":
               andorian.setVisible(true);
               break;
               
           case "Ferengi":
               ferengi.setVisible(true);
               break;
               
           case "Nibirian":
               nibirian.setVisible(true);
               break;
               
           case "Vulcanian":
               vulcanian.setVisible(true);
               break;
               
           case "Klingon":
               klingon.setVisible(true);
               break;
       }
    }//GEN-LAST:event_comboEspecieItemStateChanged

    private void slicerForçaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slicerForçaStateChanged
         jLabel2.setText(Integer.toString( slicerForça.getValue()));
    }//GEN-LAST:event_slicerForçaStateChanged

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        try{
            String valors[]= new String [8];
            valors[3] = textNom.getText();
            valors[4] = comboEspecie.getSelectedItem().toString();
            valors[5] = comboPlaneta.getSelectedItem().toString();
            switch (valors[4].toLowerCase()){
                case "huma":
                    valors[6] = textEdat.getText();
                    valors[7] = femeni.isSelected() ? femeni.getText(): masculi.getText();
                    break;
                    
                case "ferengi":
                    valors[6] = textLantanium.getText();
                    break;
                    
                case "andorian":
                    valors[6] = comboRang.getSelectedItem().toString().toLowerCase();
                    valors[7] = comboAenar.getSelectedItem().toString();
                    break;
                    
                case "klingon":
                    valors[6] = Integer.toString(slicerForça.getValue());
                    break;
                    
                case "vulcanian":
                    valors[6] = comboMeditacio.getSelectedItem().toString();
                    break;
                    
                case "nibirian":
                    valors[6] = flora.isSelected() ? "yes": "no";
                    break;
            }
            kalamusDB.escripturaEsser(valors);
             JOptionPane.showMessageDialog(null, "S'ha afegit correctament", "OK!", 1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_enviarActionPerformed
    
    private void amagar(){
        huma.setVisible(false);
        andorian.setVisible(false);
        ferengi.setVisible(false);
        nibirian.setVisible(false);
        vulcanian.setVisible(false);
        klingon.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JLabel aenar;
    private javax.swing.JLabel alimentacio;
    private javax.swing.JPanel andorian;
    private javax.swing.JComboBox<String> comboAenar;
    private javax.swing.JComboBox<String> comboEspecie;
    private javax.swing.JComboBox<String> comboMeditacio;
    private javax.swing.JComboBox<String> comboPlaneta;
    private javax.swing.JComboBox<String> comboRang;
    private javax.swing.JLabel edat;
    private javax.swing.JButton enviar;
    private javax.swing.JLabel especie;
    private javax.swing.JRadioButton femeni;
    private javax.swing.JPanel ferengi;
    private javax.swing.JRadioButton flora;
    private javax.swing.JLabel força;
    private javax.swing.JLabel genere;
    private javax.swing.ButtonGroup grup;
    private javax.swing.ButtonGroup grupNibirian;
    private javax.swing.JPanel huma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel klingon;
    private javax.swing.JLabel lantanium;
    private javax.swing.JRadioButton masculi;
    private javax.swing.JLabel meditacio;
    private javax.swing.JPanel nibirian;
    private javax.swing.JLabel nom;
    private javax.swing.JRadioButton peixos;
    private javax.swing.JLabel planeta;
    private javax.swing.JLabel rang;
    private javax.swing.JSlider slicerForça;
    private javax.swing.JTextField textEdat;
    private javax.swing.JTextField textLantanium;
    private javax.swing.JTextField textNom;
    private javax.swing.JPanel vulcanian;
    // End of variables declaration//GEN-END:variables
}
